[#p5,reftext=P.5]
=== (P.5) Required technology elements

ifdef::env-draft[]
TIP: _External systems, hardware and software, expected to be necessary for building the system. It lists external technology elements, such as program libraries and hardware devices, that the project is expected to require. Although the actual use of such products belongs to design and implementation rather than requirements, it is part of the requirements task to identify elements whose availability is critical to the success of the project — an important element of risk analysis (<<p6>>)._  <<BM22>>
endif::[]

- Compliance with external API for GPS/Map Integration:
-- This is critical for providing the main functionalities of the app, to provide nearby trails and tracking features. This will allow for real-time location tracking for users along trails, displaying shelters and safe-zones in game mode.

Impact on security:

Security concerns are relevant to the location tracking of a user, as it is critical to ensure that the API is not compromised and avoid potential risks of unauthorized access to user location data.

- Compliance with external API for HRM Integration:
-- Ensuring compatibility with different HRM devices for seamless integration and increased accessibility. Records user's activity to understand the rigour and intensity of their runs. 

Impact on security:

User's health data that is collected from the HRM devices must be handled carefully through secure data measures. 

- Compliance with external API for Payment Gateway:
-- This is critical to enable payment options and acceptance from users when they choose to make in-app purchases. This element must integrate seamlessly with the billing of various app stores.

Impact on security:

Financial transactions that are processed through the app must adhere to industry standards of secure payment,  encrypting such data. As such, protecting users' financial informations and meeting compliance standards is critical with the payment API.
