[#p6,reftext=P.6]
=== (P.6) Risk and mitigation analysis

ifdef::env-draft[]
TIP: _Potential obstacles to meeting the schedule of <<p4>>, and measures for adapting the plan if they do arise. It is essential to be on the lookout for events that could derail the project, and devise mitigation strategies. It can include a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for the project._  <<BM22>>
endif::[]

* Compatibility and Integration challenges with Heart Rate Monitors (HRM):
	One of the key features of this application is the integration of personal heart rate monitors. It relies on real time data to personalize the workouts of individuals taking advantage of this functionality. The risk here is that when users bring their own devices they may have different complex interfaces, raising the challenge of integration issues. If compatibility problems or insufficient documentation arise, it can be difficult to accomplish the integration in a specified timeline or diminishing the user experience. A mitigation strategy for this is to develop this integration early, at the start to avoid the risk of delaying the project. This allows for more time and flexibility for development and  accessing documentation. Maintaining connection to the device manufacturers to support the development and obtaining sufficient documentation would also decrease the risk. Additionally, providing a list with predefined compatible devices and instructions can reduce potential issues. 
* User Data Privacy Concerns:
	The application works by personalizing workouts for users based on their past data and usage. Collecting and storing user data such as heart rate information and location data can pose a privacy and security risk and be a concern for users. Insufficient measures to protect this data can pose risks of data breaches, violating privacy policies and regulations, as well as losing user trust. To mitigate these risks, data encryption should be prioritized, and privacy regulations should be abided throughout development. Users should consent to the terms of data collection through the app which should be transparent and clearly explained.

