[appendix]
== Implementing Feedback received

* Feedback from Window of Opportunity 1

To improve the requirements under the goals part, we modified our descriptions of the current situation, functionality overview and stakeholder tables. Previously the current situation described what the app did, so we improved it to detail why it was needed and how it addresses the current environment of the fitness industry. We also specified that the stakeholders should be distinguished between experienced and beginner runners, as well as people who simply want an affordable alternative to the gym. By doing so we were able to refine the value provided by the app to a larger audience. We visualized this with a table that wasn't included earlier. Finally, we reconsidered the key functional requirements that bring the essential value to the app, as well as redefined non-functional requirements as they were describing technical expectations previously rather than properties of the app. Reformatted the invariants section in the environment section, as well as replaced a condition with an accurate invariant of the options offered to a player based on their statistics and performance. Finally, in the project section we improved upon the risks associated with HRM integration under the risk and mitigation analysis. As well as, indicated the personas being interviewed and asked more accurate questions to the relevant stakeholders under the requirements process and report.

* Feedback from Window of Opportunity 2

Matched the stakeholders in the use cases provided with the stakeholders indicated in earlier sections to ensure consistency of the document. Provided a detailed domain model, and fine-tuned constraints that were identified to ensure clarity. Additionally, clarified the assumptions made pertaining the compatible operating systems, the role of local partners as well as catering to the usage of HRM devices. Under the system section, various improvements were made concering the API integration, mock-up wireframes, validation of functional requirements, and modifying the use-case diagrams of the detailed usage scenarios. We added the missing API that was mentionned earlier but not explained in detail under the interfaces section, and provided mock-ups of the user profile and game mode to explain the integration of various elements within the app. Improved upon how we intend to validate the achievement of the functional requirements, and ensure not to mistake with verification processes. We also udpate the use-case diagrams to show the decisions a runner can make that could lead to secondary success scenarios. Overall, the team used the provided feedback to gain better insight on the discrepencies of our report and improve in alignment with the provided instructions.

